# Generated by Django 5.0.3 on 2025-10-21 07:22

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='is_read',
            new_name='resolved',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='blood_group',
            new_name='blood_type',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='vitalrecord',
            old_name='date_recorded',
            new_name='recorded_at',
        ),
        migrations.RenameField(
            model_name='vitalrecord',
            old_name='blood_pressure',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='vitalrecord',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='vitalrecord',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='vitalrecord',
            name='weight',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='api.provider'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='hospital_name',
            field=models.CharField(default='General Hospital', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalrecord',
            name='value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalrecord',
            name='vital_type',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_records', to='api.patient'),
        ),
    ]
